create or replace view public.vw_recycle_bin_records
with (security_invoker = true)
as
  select
    pi.id,
    pi.team_id,
    'project-income'::text as source_type,
    'income'::text as type,
    pi.deleted_at,
    pi.transaction_date::timestamptz as transaction_date,
    pi.income_date::timestamptz as income_date,
    null::timestamptz as expense_date,
    null::timestamptz as due_date,
    null::timestamptz as payment_date,
    null::timestamptz as attendance_date,
    null::timestamptz as disbursed_date,
    pi.created_at,
    pi.updated_at,
    coalesce(pi.amount, 0::numeric) as amount,
    null::numeric as total_amount,
    null::numeric as total_pay,
    pi.description,
    null::text as notes,
    pi.project_name_snapshot,
    null::text as supplier_name_snapshot,
    null::text as creditor_name_snapshot,
    null::text as worker_name_snapshot,
    null::text as expense_type,
    null::text as document_type,
    null::uuid as bill_id,
    null::text as bill_type,
    null::text as bill_status,
    null::numeric as bill_amount,
    null::numeric as bill_paid_amount,
    null::numeric as bill_remaining_amount,
    null::timestamptz as bill_due_date,
    null::timestamptz as bill_paid_at,
    null::text as bill_description,
    null::text as bill_project_name_snapshot,
    null::text as bill_supplier_name_snapshot,
    null::text as bill_worker_name_snapshot,
    null::text as record_kind,
    null::uuid as expense_id,
    pi.id as project_income_id,
    pi.project_id,
    null::uuid as loan_id,
    null::uuid as worker_id,
    null::text as attendance_status,
    null::text as billing_status,
    null::uuid as salary_bill_id,
    null::numeric as principal_amount,
    null::numeric as repayment_amount,
    null::text as interest_type,
    null::numeric as interest_rate,
    null::integer as tenor_months,
    null::numeric as late_interest_rate,
    null::text as late_interest_basis,
    null::text as late_penalty_type,
    null::numeric as late_penalty_amount,
    null::jsonb as loan_terms_snapshot,
    null::text as status,
    null::numeric as paid_amount,
    null::text as original_name,
    null::text as file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(pi.description, ''),
        coalesce(pi.project_name_snapshot, '')
      )
    ) as search_text
  from public.project_incomes pi
  where pi.deleted_at is not null

  union all

  select
    e.id,
    e.team_id,
    'expense'::text as source_type,
    'expense'::text as type,
    e.deleted_at,
    e.expense_date::timestamptz as transaction_date,
    null::timestamptz as income_date,
    e.expense_date::timestamptz as expense_date,
    null::timestamptz as due_date,
    null::timestamptz as payment_date,
    null::timestamptz as attendance_date,
    null::timestamptz as disbursed_date,
    e.created_at,
    e.updated_at,
    coalesce(e.amount, e.total_amount, 0::numeric) as amount,
    coalesce(e.total_amount, e.amount, 0::numeric) as total_amount,
    null::numeric as total_pay,
    e.description,
    e.notes,
    e.project_name_snapshot,
    e.supplier_name_snapshot,
    null::text as creditor_name_snapshot,
    null::text as worker_name_snapshot,
    e.expense_type,
    e.document_type,
    null::uuid as bill_id,
    null::text as bill_type,
    null::text as bill_status,
    null::numeric as bill_amount,
    null::numeric as bill_paid_amount,
    null::numeric as bill_remaining_amount,
    null::timestamptz as bill_due_date,
    null::timestamptz as bill_paid_at,
    null::text as bill_description,
    null::text as bill_project_name_snapshot,
    null::text as bill_supplier_name_snapshot,
    null::text as bill_worker_name_snapshot,
    case
      when lower(coalesce(e.expense_type, '')) in ('material', 'material_invoice')
        or lower(coalesce(e.document_type, '')) in ('material', 'material_invoice')
      then 'material-invoice'
      else 'expense'
    end as record_kind,
    e.id as expense_id,
    null::uuid as project_income_id,
    e.project_id,
    null::uuid as loan_id,
    null::uuid as worker_id,
    null::text as attendance_status,
    null::text as billing_status,
    null::uuid as salary_bill_id,
    null::numeric as principal_amount,
    null::numeric as repayment_amount,
    null::text as interest_type,
    null::numeric as interest_rate,
    null::integer as tenor_months,
    null::numeric as late_interest_rate,
    null::text as late_interest_basis,
    null::text as late_penalty_type,
    null::numeric as late_penalty_amount,
    null::jsonb as loan_terms_snapshot,
    e.status,
    null::numeric as paid_amount,
    null::text as original_name,
    null::text as file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(e.description, ''),
        coalesce(e.notes, ''),
        coalesce(e.project_name_snapshot, ''),
        coalesce(e.supplier_name_snapshot, ''),
        coalesce(e.expense_type, ''),
        coalesce(e.document_type, '')
      )
    ) as search_text
  from public.expenses e
  where e.deleted_at is not null

  union all

  select
    l.id,
    l.team_id,
    'loan-disbursement'::text as source_type,
    'income'::text as type,
    l.deleted_at,
    l.transaction_date::timestamptz as transaction_date,
    null::timestamptz as income_date,
    null::timestamptz as expense_date,
    null::timestamptz as due_date,
    null::timestamptz as payment_date,
    null::timestamptz as attendance_date,
    l.disbursed_date::timestamptz as disbursed_date,
    l.created_at,
    l.updated_at,
    coalesce(l.principal_amount, l.amount, 0::numeric) as amount,
    null::numeric as total_amount,
    null::numeric as total_pay,
    l.description,
    l.notes,
    null::text as project_name_snapshot,
    null::text as supplier_name_snapshot,
    l.creditor_name_snapshot,
    null::text as worker_name_snapshot,
    null::text as expense_type,
    null::text as document_type,
    null::uuid as bill_id,
    null::text as bill_type,
    null::text as bill_status,
    null::numeric as bill_amount,
    null::numeric as bill_paid_amount,
    null::numeric as bill_remaining_amount,
    null::timestamptz as bill_due_date,
    null::timestamptz as bill_paid_at,
    null::text as bill_description,
    null::text as bill_project_name_snapshot,
    null::text as bill_supplier_name_snapshot,
    null::text as bill_worker_name_snapshot,
    null::text as record_kind,
    null::uuid as expense_id,
    null::uuid as project_income_id,
    null::uuid as project_id,
    l.id as loan_id,
    null::uuid as worker_id,
    null::text as attendance_status,
    null::text as billing_status,
    null::uuid as salary_bill_id,
    l.principal_amount,
    l.repayment_amount,
    l.interest_type,
    l.interest_rate,
    l.tenor_months,
    l.late_interest_rate,
    l.late_interest_basis,
    l.late_penalty_type,
    l.late_penalty_amount,
    l.loan_terms_snapshot,
    l.status,
    l.paid_amount,
    null::text as original_name,
    null::text as file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(l.description, ''),
        coalesce(l.creditor_name_snapshot, ''),
        coalesce(l.status, '')
      )
    ) as search_text
  from public.loans l
  where l.deleted_at is not null

  union all

  select
    b.id,
    b.team_id,
    'bill'::text as source_type,
    'expense'::text as type,
    b.deleted_at,
    b.due_date::timestamptz as transaction_date,
    null::timestamptz as income_date,
    null::timestamptz as expense_date,
    b.due_date::timestamptz as due_date,
    null::timestamptz as payment_date,
    null::timestamptz as attendance_date,
    null::timestamptz as disbursed_date,
    b.created_at,
    b.updated_at,
    coalesce(b.amount, 0::numeric) as amount,
    null::numeric as total_amount,
    null::numeric as total_pay,
    case
      when lower(coalesce(b.bill_type, '')) = 'gaji' then 'Tagihan Upah'
      else b.description
    end as description,
    null::text as notes,
    b.project_name_snapshot,
    b.supplier_name_snapshot,
    null::text as creditor_name_snapshot,
    b.worker_name_snapshot,
    null::text as expense_type,
    null::text as document_type,
    b.id as bill_id,
    b.bill_type,
    b.status as bill_status,
    b.amount as bill_amount,
    b.paid_amount as bill_paid_amount,
    greatest(coalesce(b.amount, 0::numeric) - coalesce(b.paid_amount, 0::numeric), 0::numeric) as bill_remaining_amount,
    b.due_date::timestamptz as bill_due_date,
    b.paid_at as bill_paid_at,
    b.description as bill_description,
    b.project_name_snapshot as bill_project_name_snapshot,
    b.supplier_name_snapshot as bill_supplier_name_snapshot,
    b.worker_name_snapshot as bill_worker_name_snapshot,
    null::text as record_kind,
    b.expense_id,
    b.project_income_id,
    null::uuid as project_id,
    null::uuid as loan_id,
    null::uuid as worker_id,
    null::text as attendance_status,
    null::text as billing_status,
    null::uuid as salary_bill_id,
    null::numeric as principal_amount,
    null::numeric as repayment_amount,
    null::text as interest_type,
    null::numeric as interest_rate,
    null::integer as tenor_months,
    null::numeric as late_interest_rate,
    null::text as late_interest_basis,
    null::text as late_penalty_type,
    null::numeric as late_penalty_amount,
    null::jsonb as loan_terms_snapshot,
    b.status,
    b.paid_amount,
    null::text as original_name,
    null::text as file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(b.description, ''),
        coalesce(b.project_name_snapshot, ''),
        coalesce(b.supplier_name_snapshot, ''),
        coalesce(b.worker_name_snapshot, ''),
        coalesce(b.bill_type, ''),
        coalesce(b.status, '')
      )
    ) as search_text
  from public.bills b
  where b.deleted_at is not null

  union all

  select
    bp.id,
    bp.team_id,
    'bill-payment'::text as source_type,
    'expense'::text as type,
    bp.deleted_at,
    bp.payment_date::timestamptz as transaction_date,
    null::timestamptz as income_date,
    null::timestamptz as expense_date,
    null::timestamptz as due_date,
    bp.payment_date::timestamptz as payment_date,
    null::timestamptz as attendance_date,
    null::timestamptz as disbursed_date,
    bp.created_at,
    bp.updated_at,
    coalesce(bp.amount, 0::numeric) as amount,
    null::numeric as total_amount,
    null::numeric as total_pay,
    bp.notes,
    bp.notes,
    bp.project_name_snapshot,
    bp.supplier_name_snapshot,
    null::text as creditor_name_snapshot,
    bp.worker_name_snapshot,
    null::text as expense_type,
    null::text as document_type,
    bp.bill_id,
    null::text as bill_type,
    null::text as bill_status,
    null::numeric as bill_amount,
    null::numeric as bill_paid_amount,
    null::numeric as bill_remaining_amount,
    null::timestamptz as bill_due_date,
    null::timestamptz as bill_paid_at,
    null::text as bill_description,
    null::text as bill_project_name_snapshot,
    null::text as bill_supplier_name_snapshot,
    null::text as bill_worker_name_snapshot,
    null::text as record_kind,
    null::uuid as expense_id,
    null::uuid as project_income_id,
    null::uuid as project_id,
    null::uuid as loan_id,
    null::uuid as worker_id,
    null::text as attendance_status,
    null::text as billing_status,
    null::uuid as salary_bill_id,
    null::numeric as principal_amount,
    null::numeric as repayment_amount,
    null::text as interest_type,
    null::numeric as interest_rate,
    null::integer as tenor_months,
    null::numeric as late_interest_rate,
    null::text as late_interest_basis,
    null::text as late_penalty_type,
    null::numeric as late_penalty_amount,
    null::jsonb as loan_terms_snapshot,
    null::text as status,
    null::numeric as paid_amount,
    null::text as original_name,
    null::text as file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(bp.notes, ''),
        coalesce(bp.supplier_name_snapshot, ''),
        coalesce(bp.worker_name_snapshot, ''),
        coalesce(bp.project_name_snapshot, ''),
        coalesce(bp.bill_id::text, '')
      )
    ) as search_text
  from public.bill_payments bp
  where bp.deleted_at is not null

  union all

  select
    lp.id,
    lp.team_id,
    'loan-payment'::text as source_type,
    'expense'::text as type,
    lp.deleted_at,
    lp.payment_date::timestamptz as transaction_date,
    null::timestamptz as income_date,
    null::timestamptz as expense_date,
    null::timestamptz as due_date,
    lp.payment_date::timestamptz as payment_date,
    null::timestamptz as attendance_date,
    null::timestamptz as disbursed_date,
    lp.created_at,
    lp.updated_at,
    coalesce(lp.amount, 0::numeric) as amount,
    null::numeric as total_amount,
    null::numeric as total_pay,
    lp.notes,
    lp.notes,
    null::text as project_name_snapshot,
    null::text as supplier_name_snapshot,
    lp.creditor_name_snapshot,
    null::text as worker_name_snapshot,
    null::text as expense_type,
    null::text as document_type,
    null::uuid as bill_id,
    null::text as bill_type,
    null::text as bill_status,
    null::numeric as bill_amount,
    null::numeric as bill_paid_amount,
    null::numeric as bill_remaining_amount,
    null::timestamptz as bill_due_date,
    null::timestamptz as bill_paid_at,
    null::text as bill_description,
    null::text as bill_project_name_snapshot,
    null::text as bill_supplier_name_snapshot,
    null::text as bill_worker_name_snapshot,
    null::text as record_kind,
    null::uuid as expense_id,
    null::uuid as project_income_id,
    null::uuid as project_id,
    lp.loan_id,
    null::uuid as worker_id,
    null::text as attendance_status,
    null::text as billing_status,
    null::uuid as salary_bill_id,
    null::numeric as principal_amount,
    null::numeric as repayment_amount,
    null::text as interest_type,
    null::numeric as interest_rate,
    null::integer as tenor_months,
    null::numeric as late_interest_rate,
    null::text as late_interest_basis,
    null::text as late_penalty_type,
    null::numeric as late_penalty_amount,
    null::jsonb as loan_terms_snapshot,
    null::text as status,
    null::numeric as paid_amount,
    null::text as original_name,
    null::text as file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(lp.notes, ''),
        coalesce(lp.creditor_name_snapshot, ''),
        coalesce(lp.amount::text, '')
      )
    ) as search_text
  from public.loan_payments lp
  inner join public.loans l
    on l.id = lp.loan_id
   and l.deleted_at is null
  where lp.deleted_at is not null

  union all

  select
    ea.id,
    ea.team_id,
    'expense-attachment'::text as source_type,
    'document'::text as type,
    ea.deleted_at,
    null::timestamptz as transaction_date,
    null::timestamptz as income_date,
    null::timestamptz as expense_date,
    null::timestamptz as due_date,
    null::timestamptz as payment_date,
    null::timestamptz as attendance_date,
    null::timestamptz as disbursed_date,
    ea.created_at,
    ea.updated_at,
    0::numeric as amount,
    null::numeric as total_amount,
    null::numeric as total_pay,
    coalesce(fa.original_name, fa.file_name, 'Lampiran') as description,
    null::text as notes,
    null::text as project_name_snapshot,
    null::text as supplier_name_snapshot,
    null::text as creditor_name_snapshot,
    null::text as worker_name_snapshot,
    null::text as expense_type,
    null::text as document_type,
    null::uuid as bill_id,
    null::text as bill_type,
    null::text as bill_status,
    null::numeric as bill_amount,
    null::numeric as bill_paid_amount,
    null::numeric as bill_remaining_amount,
    null::timestamptz as bill_due_date,
    null::timestamptz as bill_paid_at,
    null::text as bill_description,
    null::text as bill_project_name_snapshot,
    null::text as bill_supplier_name_snapshot,
    null::text as bill_worker_name_snapshot,
    null::text as record_kind,
    ea.expense_id,
    null::uuid as project_income_id,
    null::uuid as project_id,
    null::uuid as loan_id,
    null::uuid as worker_id,
    null::text as attendance_status,
    null::text as billing_status,
    null::uuid as salary_bill_id,
    null::numeric as principal_amount,
    null::numeric as repayment_amount,
    null::text as interest_type,
    null::numeric as interest_rate,
    null::integer as tenor_months,
    null::numeric as late_interest_rate,
    null::text as late_interest_basis,
    null::text as late_penalty_type,
    null::numeric as late_penalty_amount,
    null::jsonb as loan_terms_snapshot,
    null::text as status,
    null::numeric as paid_amount,
    fa.original_name,
    fa.file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(fa.original_name, ''),
        coalesce(fa.file_name, ''),
        coalesce(ea.expense_id::text, '')
      )
    ) as search_text
  from public.expense_attachments ea
  left join public.file_assets fa
    on fa.id = ea.file_asset_id
  where ea.deleted_at is not null

  union all

  select
    ar.id,
    ar.team_id,
    'attendance-record'::text as source_type,
    'expense'::text as type,
    ar.deleted_at,
    ar.attendance_date::timestamptz as transaction_date,
    null::timestamptz as income_date,
    null::timestamptz as expense_date,
    null::timestamptz as due_date,
    null::timestamptz as payment_date,
    ar.attendance_date::timestamptz as attendance_date,
    null::timestamptz as disbursed_date,
    ar.created_at,
    ar.updated_at,
    coalesce(ar.total_pay, 0::numeric) as amount,
    null::numeric as total_amount,
    coalesce(ar.total_pay, 0::numeric) as total_pay,
    ar.notes,
    ar.notes,
    ar.project_name_snapshot,
    null::text as supplier_name_snapshot,
    null::text as creditor_name_snapshot,
    ar.worker_name_snapshot,
    null::text as expense_type,
    null::text as document_type,
    null::uuid as bill_id,
    null::text as bill_type,
    null::text as bill_status,
    null::numeric as bill_amount,
    null::numeric as bill_paid_amount,
    null::numeric as bill_remaining_amount,
    null::timestamptz as bill_due_date,
    null::timestamptz as bill_paid_at,
    null::text as bill_description,
    null::text as bill_project_name_snapshot,
    null::text as bill_supplier_name_snapshot,
    null::text as bill_worker_name_snapshot,
    null::text as record_kind,
    null::uuid as expense_id,
    null::uuid as project_income_id,
    ar.project_id,
    null::uuid as loan_id,
    ar.worker_id,
    ar.attendance_status,
    ar.billing_status,
    ar.salary_bill_id,
    null::numeric as principal_amount,
    null::numeric as repayment_amount,
    null::text as interest_type,
    null::numeric as interest_rate,
    null::integer as tenor_months,
    null::numeric as late_interest_rate,
    null::text as late_interest_basis,
    null::text as late_penalty_type,
    null::numeric as late_penalty_amount,
    null::jsonb as loan_terms_snapshot,
    null::text as status,
    null::numeric as paid_amount,
    null::text as original_name,
    null::text as file_name,
    lower(
      concat_ws(
        ' ',
        coalesce(ar.notes, ''),
        coalesce(ar.worker_name_snapshot, ''),
        coalesce(ar.project_name_snapshot, '')
      )
    ) as search_text
  from public.attendance_records ar
  where ar.deleted_at is not null
    and ar.billing_status = 'unbilled'
    and ar.salary_bill_id is null;

grant select on table public.vw_recycle_bin_records to anon, authenticated;
